# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0005_auto_20161006_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profileinfo',
            name='last_name',
        ),
    ]
