# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0008_auto_20161021_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
