# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0009_auto_20161022_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='last_modified',
        ),
    ]
