# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0010_remove_blog_last_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileinfo',
            name='follower',
        ),
        migrations.AlterField(
            model_name='profileinfo',
            name='following',
            field=models.ManyToManyField(related_name='follower', to='grumblr.Profileinfo'),
        ),
    ]
